# Generated by Django 4.1 on 2022-08-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(blank=True, max_length=255, null=True)),
                ("type", models.IntegerField(blank=True, null=True)),
                (
                    "access_list",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("block_hash", models.CharField(blank=True, max_length=255, null=True)),
                ("block_number", models.IntegerField(blank=True, null=True)),
                (
                    "from_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("to_address", models.CharField(blank=True, max_length=255, null=True)),
                ("chain_id", models.IntegerField(blank=True, null=True)),
                ("confirmations", models.IntegerField(blank=True, null=True)),
                ("creates", models.CharField(blank=True, max_length=255, null=True)),
                ("data", models.CharField(blank=True, max_length=255, null=True)),
                ("gasLimit", models.CharField(blank=True, max_length=255, null=True)),
                ("gasPrice", models.CharField(blank=True, max_length=255, null=True)),
                ("nonce", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.IntegerField(blank=True, null=True)),
                ("transactionIndex", models.IntegerField(blank=True, null=True)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "transaction",
            },
        ),
    ]
